### PR TITLE
CI: Annotate errors for Github

### PR DESCRIPTION
**Pull request by runephilosof-abtion**
As described on
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions

### CODE REVIEW

**Comment by runephilosof-abtion** [comment]
The annotations are not visible on "conversation" tab of a PR.
image

But they are visible on "Files changed"
image

**Comment by jeppester** [comment]
Looks like a fine little improvement.
To ensure that the rspec formatter works, could you make a commit that breaks rspec?

**Comment by runephilosof-abtion** [comment]
Made rspec fail in #2329 
It annotates the rspec files with the errors, instead of the place where the error is raised, but I guess it is better than not annotating.

image

**Comment by runephilosof-abtion** [comment]
The gem maintainer is open to adding annotating the exception file/line
https://github.com/Drieam/rspec-github/issues/75
https://github.com/Drieam/rspec-github/pull/76/files

**Comment by jeppester** [comment]
> The gem maintainer is open to adding annotating the exception file/line
> [Drieam/rspec-github#75](https://github.com/Drieam/rspec-github/issues/75)
> https://github.com/Drieam/rspec-github/pull/76/files

Cool.

I don't like for this PR to stall while we are waiting, let's merge this for the value it gives us already.
Then we can upgrade if it becomes possible to show the exception location.

**Review by jeppester — APPROVED** [review]

**Comment by jeppester** [comment]
@runephilosof-abtion Would you prefer to not merge this just yet?

**Pull request merged**
